### ISSUE TITLE
sbt-statika: what goes here, what not

### ISSUE THREAD

**Issue by eparejatobes** [ohnosequences/sbt-statika#5]
This project should help _only_ in developing bundles, _not_ in testing them. Now if my understanding is OK (@laughedelic?) we will keep here
- bundle metadata generation?
- fat jar stuff?

and I guess that's all. What happens with the launching instances part? 
- if it is related with testing compatibility and such, goes to bioinfo (either directly in the build file or as a plugin)
- if it's about generating instance specs and such, we don't need any sbt-level thing. Just expand `aws-statika` if needed

**Comment by laughedelic** [comment]
Could you clarify the second part? where is the launching code now?

**Comment by eparejatobes** [comment]
launching code for what?

**Comment by eparejatobes** [comment]
I mean, aws-statika gives you instance specs for a bundle; what else is needed?

**Comment by laughedelic** [comment]
the code that will _launch_ an instance (or make a spot request) with those specs

**Comment by eparejatobes** [comment]
For era7 projects I will write a mini-lib.

**Comment by eparejatobes** [comment]
https://github.com/era7bio/project-utils

**Comment by laughedelic** [comment]
[okay...](http://1.bp.blogspot.com/-g1tICB6XFjE/TuHh9GBlv8I/AAAAAAAADLg/B3fO8ry2tjc/s1600/Okay_guy.jpg)
